version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=movie_theater
      - JWT_SECRET=dev_secret_key
      - JWT_EXPIRATION=24h
      - LOG_LEVEL=debug
      - CORS_ORIGIN=http://localhost:3000
      - RATE_LIMIT_TTL=60
      - RATE_LIMIT_LIMIT=100
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "yarn workspace @project-nest/api migration:run && yarn workspace @project-nest/api seed && yarn workspace @project-nest/api start:dev"

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movie_theater
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
